[project]
name = "nullbr-python"
version = "0.1.0"
description = "nullbr python sdk"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "httpx[http2]>=0.28.1",
    "python-dotenv>=1.1.0",
]
